### ISSUE TITLE
Need update for Spring Framework 2.2

### ISSUE THREAD

**Issue by cookietx** [davidkiss/spring-cloud-streams-kafka-demo#3]
Is there any update for Spring framework version 2.2?  I tried to update the sample for that version but keep running into an error "Magic v1 does not support record headers" when trying to send the message.

**Comment by davidkiss** [comment]
Can you check this spring cloud ticket, it may have a solution to your problem: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/290?

**Comment by davidkiss** [comment]
If it helps, please submit a PR with your changes

**Comment by cookietx** [comment]
Old verion of Kafka, kafka_2.12-0.10.2.1.tgz, is not compatible with the kafka-client 2.3.1 that comes with Spring Framework 2.2
I moved to the latest of Kafka, kafka_2.12-2.3.1.tgz, and then recreated the pom.xml file using start.spring.io.  It is attached.
All works as expected now.

    On Friday, November 22, 2019, 11:38:49 AM CST, David Kiss <notifications@github.com> wrote:  
 
 
Can you check this spring cloud ticket, it may have a solution to your problem: spring-cloud/spring-cloud-stream-binder-kafka#290?

**Comment by davidkiss** [comment]
Glad to hear it works for you now.
